my:
  greeting: Hello World from spring-cloud-config-clien!

server:
  port: 8089

spring:
  cloud:
    config:
      uri: http://localhost:${config.port}

# Actuator allow all for dev
management:
  endpoints:
    web:
      exposure:
        include: "*"
