# This config needs SpringCloudConfigServerApplication (spring-cloud-config-server) UP && Running
# Also needs "${HOME}/src/github/configrepo" with the values updated
server:
  port: ${server.port}

my:
  greeting: ${greeting}
  message: ${message}

spring:
  application:
    name: spring-cloud-config-client-dev
  cloud:
    config:
      uri: http://localhost:${config.port}

# Actuator allow all for dev
management:
  endpoints:
    web:
      exposure:
        include: "*"

